name: ci

on:
    push:

jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: List directory contents
              run: |
                  echo "Current directory:"
                  pwd
                  echo "Directory contents:"
                  ls -R
            - name: Build and push
              uses: docker/build-push-action@v6
              with:
                  context: .
                  file: ./packages/pkg-a/Dockerfile
                  push: true
                  tags: |
                      handlebauer/docker-workspace:latest
                      handlebauer/docker-workspace:${{ github.sha }}
